
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy rustfmt
    - name: Clippy (all)
      run: cargo clippy --all-features -- -D warnings
    - name: Rustfmt
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests
      run: cargo test --no-default-features --verbose
    - name: Run tests with all features
      run: cargo test --all-features --verbose
    - name: Run benchmarks
      run: cargo bench